# Generated by Django 4.1.7 on 2023-03-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_post_host_comment_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
