# Generated by Django 4.1.7 on 2023-03-19 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_post_name_remove_post_topic_delete_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-update', '-created']},
        ),
    ]
