# Generated by Django 4.1.7 on 2023-03-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
